services:
  - type: web
    name: dqms-memorix
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn core.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 120
    envVars:
      - key: DEBUG
        value: "False"
      - key: USE_SQLITE
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "*"
      - key: CSRF_TRUSTED_ORIGINS
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: dqms-db
          property: connectionString
      - key: GEMINI_API_KEY
        sync: false
      - key: GEMINI_MODEL
        value: gemini-2.5-flash
      - key: XAI_API_KEY
        sync: false
      - key: XAI_MODEL
        value: grok-4.3
      - key: XAI_BASE_URL
        value: https://api.x.ai/v1
      - key: SITE_URL
        sync: false

databases:
  - name: dqms-db
    plan: free
