# Generated by Django 4.2.11 on 2026-05-11 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='ai_explanation',
            field=models.TextField(blank=True),
        ),
    ]
