# Generated by Django 4.2.11 on 2026-05-09 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PointEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('reason', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('topic_bronze', 'Topic Bronze (10 topics)'), ('topic_silver', 'Topic Silver (25 topics)'), ('topic_gold', 'Topic Gold (50 topics)'), ('topic_diamond', 'Topic Diamond (100 topics)'), ('points_bronze', 'Points Bronze (100)'), ('points_silver', 'Points Silver (300)'), ('points_gold', 'Points Gold (600)'), ('points_diamond', 'Points Diamond (1000)'), ('streak_7', '7-Day Streak'), ('streak_30', '30-Day Streak')], max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(default='🏅', max_length=10)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-earned_at'],
                'unique_together': {('user', 'kind')},
            },
        ),
    ]
